In [1]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
#import dataet
dataset=pd.read_csv("data.csv")
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [5]:
#identify independent variable
#x=dataset[['Country','Age','Salary']].values
x=dataset.iloc[:,0:3].values
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
#idenfity dependent variable
#y=dataset[['Purchased']].values
y=dataset.iloc[:,-1].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [11]:
#find missing value
dataset.isnull()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [13]:
#replace missing variable
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:,1:3])
x[:,1:3]=imputer.fit_transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [14]:
#encoding categorical variable
#for dependent variable- y
from sklearn.preprocessing import LabelEncoder
laberencode_y=LabelEncoder()
y=laberencode_y.fit_transform(y)
print(y)


[0 1 0 0 1 1 0 1 0 1]


In [16]:
#encoding categorical variable
#for independent variable -x
from sklearn.preprocessing import OneHotEncoder
onehotencoder_x=OneHotEncoder()
x=onehotencoder_x.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()
print(x)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [23]:
#splitting dataset into training and testing set
from sklearn.model_selection import train_test_split
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[0 0]


In [30]:
#features scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
#x_test=sc_x.transform(x_test)
print(x_train)
print(x_test)

[[-1.          2.64575131 -0.77459667]
 [ 1.         -0.37796447 -0.77459667]
 [-1.         -0.37796447  1.29099445]
 [-1.         -0.37796447  1.29099445]
 [ 1.         -0.37796447 -0.77459667]
 [-1.         -0.37796447  1.29099445]
 [ 1.         -0.37796447 -0.77459667]
 [ 1.         -0.37796447 -0.77459667]]
[1 1 1 0 1 0 0 1]


In [ ]:
#end our model are ready-------------------------